name: cs324
channels:
  - pytorch
  - huggingface
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - cpuonly
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - datasets
  - transformers
  - tqdm
  - scikit-learn
  - transformers
  - datasets
  - ipykernel
  - pip
