name: cs324
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - pytorch-cuda=11.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - datasets
  - transformers
  - tqdm
  - scikit-learn
  - transformers
  - datasets
  - ipykernel
  - pip
